# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hwolff <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/02/25 21:06:23 by hwolff            #+#    #+#              #
#    Updated: 2018/02/27 13:26:41 by hwolff           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME =			colle-2
SRCFILE =		main.c algo.c ft_putchar.c rush00.c rush01.c rush02.c rush03.c \
				rush04.c rush-00 rush-01 rush-02 rush-03 rush-04
SRCDIR =		./srcs/
HEADERPATH =	./includes/
SRCS =			$(addprefix $(SRCDIR), $(SRCFILE))
OBJS =			$(SRCFILE:.c=.o)
CC =			gcc
CFLAGS =		-Wall -Wextra -Werror

all: $(NAME)

